/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypeRouteImport } from './routes/type'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypeIndexRouteImport } from './routes/type/index'
import { Route as TypeNewRouteImport } from './routes/type/new'
import { Route as TypeIdRouteImport } from './routes/type/$id'
import { Route as MatrixNewRouteImport } from './routes/matrix/new'
import { Route as MatrixIdRouteImport } from './routes/matrix/$id'
import { Route as DeckNewRouteImport } from './routes/deck/new'
import { Route as DeckIdRouteImport } from './routes/deck/$id'

const TypeRoute = TypeRouteImport.update({
  id: '/type',
  path: '/type',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeIndexRoute = TypeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TypeRoute,
} as any)
const TypeNewRoute = TypeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TypeRoute,
} as any)
const TypeIdRoute = TypeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TypeRoute,
} as any)
const MatrixNewRoute = MatrixNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MatrixRoute,
} as any)
const MatrixIdRoute = MatrixIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MatrixRoute,
} as any)
const DeckNewRoute = DeckNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DeckRoute,
} as any)
const DeckIdRoute = DeckIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeckRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck': typeof DeckRouteWithChildren
  '/home': typeof HomeRoute
  '/matrix': typeof MatrixRouteWithChildren
  '/settings': typeof SettingsRoute
  '/type': typeof TypeRouteWithChildren
  '/deck/$id': typeof DeckIdRoute
  '/deck/new': typeof DeckNewRoute
  '/matrix/$id': typeof MatrixIdRoute
  '/matrix/new': typeof MatrixNewRoute
  '/type/$id': typeof TypeIdRoute
  '/type/new': typeof TypeNewRoute
  '/type/': typeof TypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck': typeof DeckRouteWithChildren
  '/home': typeof HomeRoute
  '/matrix': typeof MatrixRouteWithChildren
  '/settings': typeof SettingsRoute
  '/deck/$id': typeof DeckIdRoute
  '/deck/new': typeof DeckNewRoute
  '/matrix/$id': typeof MatrixIdRoute
  '/matrix/new': typeof MatrixNewRoute
  '/type/$id': typeof TypeIdRoute
  '/type/new': typeof TypeNewRoute
  '/type': typeof TypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck': typeof DeckRouteWithChildren
  '/home': typeof HomeRoute
  '/matrix': typeof MatrixRouteWithChildren
  '/settings': typeof SettingsRoute
  '/type': typeof TypeRouteWithChildren
  '/deck/$id': typeof DeckIdRoute
  '/deck/new': typeof DeckNewRoute
  '/matrix/$id': typeof MatrixIdRoute
  '/matrix/new': typeof MatrixNewRoute
  '/type/$id': typeof TypeIdRoute
  '/type/new': typeof TypeNewRoute
  '/type/': typeof TypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deck'
    | '/home'
    | '/matrix'
    | '/settings'
    | '/type'
    | '/deck/$id'
    | '/deck/new'
    | '/matrix/$id'
    | '/matrix/new'
    | '/type/$id'
    | '/type/new'
    | '/type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deck'
    | '/home'
    | '/matrix'
    | '/settings'
    | '/deck/$id'
    | '/deck/new'
    | '/matrix/$id'
    | '/matrix/new'
    | '/type/$id'
    | '/type/new'
    | '/type'
  id:
    | '__root__'
    | '/'
    | '/deck'
    | '/home'
    | '/matrix'
    | '/settings'
    | '/type'
    | '/deck/$id'
    | '/deck/new'
    | '/matrix/$id'
    | '/matrix/new'
    | '/type/$id'
    | '/type/new'
    | '/type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckRoute: typeof DeckRouteWithChildren
  HomeRoute: typeof HomeRoute
  MatrixRoute: typeof MatrixRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TypeRoute: typeof TypeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/type': {
      id: '/type'
      path: '/type'
      fullPath: '/type'
      preLoaderRoute: typeof TypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type/': {
      id: '/type/'
      path: '/'
      fullPath: '/type/'
      preLoaderRoute: typeof TypeIndexRouteImport
      parentRoute: typeof TypeRoute
    }
    '/type/new': {
      id: '/type/new'
      path: '/new'
      fullPath: '/type/new'
      preLoaderRoute: typeof TypeNewRouteImport
      parentRoute: typeof TypeRoute
    }
    '/type/$id': {
      id: '/type/$id'
      path: '/$id'
      fullPath: '/type/$id'
      preLoaderRoute: typeof TypeIdRouteImport
      parentRoute: typeof TypeRoute
    }
    '/matrix/new': {
      id: '/matrix/new'
      path: '/new'
      fullPath: '/matrix/new'
      preLoaderRoute: typeof MatrixNewRouteImport
      parentRoute: typeof MatrixRoute
    }
    '/matrix/$id': {
      id: '/matrix/$id'
      path: '/$id'
      fullPath: '/matrix/$id'
      preLoaderRoute: typeof MatrixIdRouteImport
      parentRoute: typeof MatrixRoute
    }
    '/deck/new': {
      id: '/deck/new'
      path: '/new'
      fullPath: '/deck/new'
      preLoaderRoute: typeof DeckNewRouteImport
      parentRoute: typeof DeckRoute
    }
    '/deck/$id': {
      id: '/deck/$id'
      path: '/$id'
      fullPath: '/deck/$id'
      preLoaderRoute: typeof DeckIdRouteImport
      parentRoute: typeof DeckRoute
    }
  }
}

interface DeckRouteChildren {
  DeckIdRoute: typeof DeckIdRoute
  DeckNewRoute: typeof DeckNewRoute
}

const DeckRouteChildren: DeckRouteChildren = {
  DeckIdRoute: DeckIdRoute,
  DeckNewRoute: DeckNewRoute,
}

const DeckRouteWithChildren = DeckRoute._addFileChildren(DeckRouteChildren)

interface MatrixRouteChildren {
  MatrixIdRoute: typeof MatrixIdRoute
  MatrixNewRoute: typeof MatrixNewRoute
}

const MatrixRouteChildren: MatrixRouteChildren = {
  MatrixIdRoute: MatrixIdRoute,
  MatrixNewRoute: MatrixNewRoute,
}

const MatrixRouteWithChildren =
  MatrixRoute._addFileChildren(MatrixRouteChildren)

interface TypeRouteChildren {
  TypeIdRoute: typeof TypeIdRoute
  TypeNewRoute: typeof TypeNewRoute
  TypeIndexRoute: typeof TypeIndexRoute
}

const TypeRouteChildren: TypeRouteChildren = {
  TypeIdRoute: TypeIdRoute,
  TypeNewRoute: TypeNewRoute,
  TypeIndexRoute: TypeIndexRoute,
}

const TypeRouteWithChildren = TypeRoute._addFileChildren(TypeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckRoute: DeckRouteWithChildren,
  HomeRoute: HomeRoute,
  MatrixRoute: MatrixRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TypeRoute: TypeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
